export const starterExercises = [
  {
    name: 'Barbell Flat Bench Press',
    targetMuscleGroup: 'chest',
    secondaryMuscles: ['shoulders', 'arms'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: [
      'Lie flat on the bench with eyes directly under the racked bar.',
      'Grip the bar slightly wider than shoulder-width, wrists neutral.',
      'Unrack, take a deep breath into your diaphragm, and pull the bar smoothly down to mid-chest.',
      'Press explosively upward until arms are extended, driving through your legs without lifting your glutes off the bench.',
    ],
    formCues: ['Retract scapula together', 'Keep elbows at a 45-degree angle', 'Plant feet firmly on the floor'],
    precautions: 'Do not bounce the bar off your sternum. Use safety spotter arms when training heavy.',
  },
  {
    name: 'Incline Dumbbell Chest Press',
    targetMuscleGroup: 'chest',
    secondaryMuscles: ['shoulders', 'arms'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: [
      'Set an adjustable bench to approximately 30 degrees incline.',
      'Kick dumbbells to shoulder height as you lie back against the pad.',
      'Lower the dumbbells in a controlled motion until elbows reach roughly 90 degrees.',
      'Press upward in an arc without clanking the weights at the top.',
    ],
    formCues: ['Do not set incline too steep (avoid front delt dominance)', 'Keep wrist stacked over elbow'],
    precautions: 'Avoid letting your elbows flare straight out sideways to preserve rotator cuff integrity.',
  },
  {
    name: 'Pull-Up',
    targetMuscleGroup: 'back',
    secondaryMuscles: ['arms', 'core'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: [
      'Hang from an overhead pull-up bar with an overhand grip wider than shoulders.',
      'Depress shoulder blades down, engage core, and pull chest towards the bar.',
      'Pause momentarily when chin clears the bar, then lower with full control to dead hang.',
    ],
    formCues: ['Do not kick or swing your legs', 'Drive elbows straight down towards ribs'],
    precautions: 'If struggling to reach full range of motion, use a resistance band or assisted machine.',
  },
  {
    name: 'Barbell Bent-Over Row',
    targetMuscleGroup: 'back',
    secondaryMuscles: ['arms', 'core'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: [
      'Hinge at hips with soft knees, back flat, torso angled roughly 45 degrees to floor.',
      'Grip bar slightly wider than shoulder width.',
      'Pull barbell towards lower abdomen/navel, squeezing your shoulder blades together.',
      'Lower the weight smoothly under control without rounding lower spine.',
    ],
    formCues: ['Keep neck neutral, do not look straight up', 'Keep bar close to thighs on the way up'],
    precautions: 'Keep weight modest until you maintain strict lumbar curvature throughout all sets.',
  },
  {
    name: 'Barbell Back Squat',
    targetMuscleGroup: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: [
      'Rest barbell securely across upper traps in squat rack.',
      'Step back, stance shoulder-width apart, toes flared slightly out.',
      'Brace core, sit hips down and back until hip crease is parallel to knee crease.',
      'Drive powerfully out of the hole, keeping chest tall and knees tracking over toes.',
    ],
    formCues: ['Push knees out in line with toes', 'Maintain tripod foot pressure', 'Brace core with Valsalva'],
    precautions: 'Do not allow lower back to round (butt wink) at the bottom. Adjust depth to mobility.',
  },
  {
    name: 'Romanian Deadlift (RDL)',
    targetMuscleGroup: 'legs',
    secondaryMuscles: ['back', 'core'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: [
      'Stand holding barbell at thighs with an overhand grip.',
      'Keep slight knee bend, push hips straight backward as if touching a wall behind you.',
      'Lower bar along shins until you feel an intense stretch in hamstrings.',
      'Drive hips forward to return to standing lockout.',
    ],
    formCues: ['Think of hip hinge rather than squatting down', 'Keep bar glued to your legs'],
    precautions: 'Do not let barbell drift away from your body as it puts torque on lower lumbar.',
  },
  {
    name: 'Overhead Barbell Shoulder Press',
    targetMuscleGroup: 'shoulders',
    secondaryMuscles: ['arms', 'core'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: [
      'Rest bar on front delts with hands just outside shoulders.',
      'Squeeze glutes and brace abs.',
      'Press bar vertically overhead, moving head slightly back to let bar pass, then forward once cleared.',
      'Lock out with arms in line with ears.',
    ],
    formCues: ['Do not overarch lower back', 'Squeeze glutes firmly for trunk stability'],
    precautions: 'Never drop bar behind the neck.',
  },
  {
    name: 'Dumbbell Lateral Raise',
    targetMuscleGroup: 'shoulders',
    secondaryMuscles: ['arms'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: [
      'Stand with dumbbells at sides, slight forward torso tilt.',
      'Raise dumbbells out to sides leading with elbows until parallel with floor.',
      'Pause briefly at apex, then resist gravity on the descent.',
    ],
    formCues: ['Pour the pitcher cue: thumbs slightly lower than pinkies', 'Avoid shrugging traps upward'],
    precautions: 'Use light weight with strict technique; swinging damages shoulder joints.',
  },
  {
    name: 'Standing Dumbbell Bicep Curl',
    targetMuscleGroup: 'arms',
    secondaryMuscles: ['core'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: [
      'Hold dumbbells by sides with palms facing each other.',
      'Curl weights upward while supinating wrists so palms face shoulders at top.',
      'Squeeze biceps at peak contraction, then lower slowly over 2-3 seconds.',
    ],
    formCues: ['Pin elbows to your ribcage', 'Do not lean back or rock torso'],
    precautions: 'Avoid hyperextending elbows at the bottom of the movement.',
  },
  {
    name: 'Cable Tricep Rope Pushdown',
    targetMuscleGroup: 'arms',
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: [
      'Attach rope to high pulley and grip near the rubber knots.',
      'Pin elbows to sides, lean forward slightly from hips.',
      'Extend forearms downward, spreading rope ends apart at full lockout.',
      'Return to 90 degrees elbow bend under control.',
    ],
    formCues: ['Isolate the elbow joint only', 'Squeeze triceps at bottom extension'],
    precautions: 'Do not let shoulders roll forward to press down using chest weight.',
  },
  {
    name: 'Hanging Knee / Leg Raise',
    targetMuscleGroup: 'core',
    secondaryMuscles: ['arms'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: [
      'Hang from pull-up bar with overhand grip and engaged shoulders.',
      'Posteriorly tilt pelvis and lift knees/legs toward chest.',
      'Hold top contraction for a second, then lower steadily without swinging.',
    ],
    formCues: ['Curl pelvis up rather than just swinging legs', 'Control descent to eliminate momentum'],
    precautions: 'Do not let body swing like a pendulum.',
  },
  {
    name: 'Cable Lat Pulldown',
    targetMuscleGroup: 'back',
    secondaryMuscles: ['arms'],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: [
      'Adjust thigh pad firmly, sit and grip wide bar with palms forward.',
      'Lean back slightly (10-15 degrees), pull bar down smoothly towards upper clavicle.',
      'Squeeze lats at bottom, then smoothly let bar rise until lats are stretched.',
    ],
    formCues: ['Drive elbows down and back', 'Keep chest proud toward ceiling'],
    precautions: 'Never pull the bar behind the back of the head.',
  },
];

export const starterSupplements = [
  {
    name: 'Whey Protein Isolate / Concentrate',
    category: 'protein',
    estimatedPriceMin: 1800,
    estimatedPriceMax: 3500,
    purpose: 'Convenient dietary protein supplementation to support muscle repair and daily protein targets.',
    usageGuidance: 'Typically 1 scoop (20-25g protein) post-workout or between meals when whole-food protein is unavailable.',
    foodAlternatives: ['Chicken breast (100g = ~31g protein)', 'Paneer / Cottage cheese / Soya chunks', 'Eggs and egg whites', 'Tofu & Moong dal sprouts'],
    allergenInfo: ['Contains dairy / lactose (isolate has lower lactose)'],
  },
  {
    name: 'Creatine Monohydrate',
    category: 'creatine',
    estimatedPriceMin: 600,
    estimatedPriceMax: 1200,
    purpose: 'Enhances cellular ATP regeneration, assisting maximal power output, strength, and lean mass gain.',
    usageGuidance: '3 to 5 grams daily consistently at any time with ample water. Loading phase is optional.',
    foodAlternatives: ['Herring, salmon, and red meat naturally contain small amounts (~1g per 200g serving).'],
    allergenInfo: ['Generally allergen-free, vegan synthetic synthesis common.'],
  },
  {
    name: 'Electrolyte & Hydration Complex',
    category: 'recovery',
    estimatedPriceMin: 350,
    estimatedPriceMax: 750,
    purpose: 'Replenishes sodium, potassium, and magnesium lost through prolonged intense sweating.',
    usageGuidance: 'Mix with water during long sessions or in hot training environments.',
    foodAlternatives: ['Bananas (potassium)', 'Coconut water', 'Salted buttermilk (Chaas)', 'Spinach / Leafy greens (magnesium)'],
    allergenInfo: ['Check for artificial sweeteners or food colorings if sensitive.'],
  },
  {
    name: 'Omega-3 Fish Oil',
    category: 'micronutrients',
    estimatedPriceMin: 500,
    estimatedPriceMax: 1100,
    purpose: 'Supports cardiovascular health, joint mobility, and healthy inflammatory response.',
    usageGuidance: '1-2 capsules daily with a whole fat-containing meal.',
    foodAlternatives: ['Flaxseeds, chia seeds, walnuts (vegetarian ALA)', 'Mackerel, sardines, rohu/katla fish'],
    allergenInfo: ['Fish / Shellfish (Algae oil is plant-based alternative)'],
  },
];

export const defaultGymSchedule = [
  { dayOfWeek: 0, dayName: 'Sunday', isOpen: true, openTime: '08:00', closeTime: '18:00' },
  { dayOfWeek: 1, dayName: 'Monday', isOpen: true, openTime: '06:00', closeTime: '22:00' },
  { dayOfWeek: 2, dayName: 'Tuesday', isOpen: true, openTime: '06:00', closeTime: '22:00' },
  { dayOfWeek: 3, dayName: 'Wednesday', isOpen: true, openTime: '06:00', closeTime: '22:00' },
  { dayOfWeek: 4, dayName: 'Thursday', isOpen: true, openTime: '06:00', closeTime: '22:00' },
  { dayOfWeek: 5, dayName: 'Friday', isOpen: true, openTime: '06:00', closeTime: '22:00' },
  { dayOfWeek: 6, dayName: 'Saturday', isOpen: true, openTime: '07:00', closeTime: '20:00' },
];
